INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(1,10,144.968,-37.8497,'Australia','Albert Park Grand Prix Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(2,18,101.738,2.76083,'Malaysia','Sepang International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(3,7,50.5106,26.0325,'Bahrain','Bahrain International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(4,109,2.26111,41.57,'Spain','Circuit de Barcelona-Catalunya');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(5,130,29.405,40.9517,'Turkey','Istanbul Park');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(6,7,7.42056,43.7347,'Monaco','Circuit de Monaco');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(7,13,-73.5228,45.5,'Canada','Circuit Gilles Villeneuve');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(8,228,3.16361,46.8642,'France','Circuit de Nevers Magny-Cours');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(9,153,-1.01694,52.0786,'UK','Silverstone Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(10,103,8.56583,49.3278,'Germany','Hockenheimring');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(11,264,19.2486,47.5789,'Hungary','Hungaroring');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(12,4,-0.331667,39.4589,'Spain','Valencia Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(13,401,5.97139,50.4372,'Belgium','Circuit de Spa-Francorchamps');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(14,162,9.28111,45.6156,'Italy','Autodromo Nazionale di Monza');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(15,18,103.864,1.2914,'Singapore','Marina Bay Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(16,583,138.927,35.3717,'Japan','Fuji Speedway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(17,5,121.22,31.3389,'China','Shanghai International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(18,785,-46.6997,-23.7036,'Brazil','Autódromo José Carlos Pace');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(19,223,-86.2347,39.795,'USA','Indianapolis Motor Speedway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(20,578,6.9475,50.3356,'Germany','Nürburgring');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(21,37,11.7167,44.3439,'Italy','Autodromo Enzo e Dino Ferrari');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(22,45,136.541,34.8431,'Japan','Suzuka Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(80,642,-115.173,36.1147,'United States','Las Vegas Strip Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(24,3,54.6031,24.4672,'UAE','Yas Marina Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(25,8,-58.4593,-34.6943,'Argentina','Autódromo Juan y Oscar Gálvez');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(26,37,-6.03417,36.7083,'Spain','Circuito de Jerez');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(27,130,-9.39417,38.7506,'Portugal','Autódromo do Estoril');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(28,266,134.221,34.915,'Japan','Okayama International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(29,58,138.617,-34.9272,'Australia','Adelaide Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(30,1460,28.0767,-25.9894,'South Africa','Kyalami');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(31,88,-1.37528,52.8306,'UK','Donington Park');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(32,2227,-99.0907,19.4042,'Mexico','Autódromo Hermanos Rodríguez');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(33,345,-112.075,33.4479,'USA','Phoenix street circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(34,432,5.79167,43.2506,'France','Circuit Paul Ricard');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(35,0,126.417,34.7333,'Korea','Korean International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(36,1126,-43.395,-22.9756,'Brazil','Autódromo Internacional Nelson Piquet');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(37,177,-83.0401,42.3298,'USA','Detroit Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(38,145,0.263056,51.3569,'UK','Brands Hatch');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(39,6,4.54092,52.3888,'Netherlands','Circuit Park Zandvoort');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(40,36,5.25694,50.9894,'Belgium','Zolder');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(41,484,4.89913,47.3625,'France','Dijon-Prenois');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(42,139,-96.7587,32.7774,'USA','Fair Park');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(43,12,-118.189,33.7651,'USA','Long Beach');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(44,639,-115.174,36.1162,'USA','Las Vegas Street Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(45,609,-3.58558,40.6171,'Spain','Jarama');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(46,485,-76.9272,42.3369,'USA','Watkins Glen');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(47,153,13.6042,57.2653,'Sweden','Scandinavian Raceway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(48,332,-78.6756,44.0481,'Canada','Mosport International Raceway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(49,79,2.15167,41.3664,'Spain','Montjuïc');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(50,139,4.32694,50.6211,'Belgium','Nivelles-Baulers');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(51,790,3.03889,45.7472,'France','Charade Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(52,214,-74.6099,46.1877,'Canada','Circuit Mont-Tremblant');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(53,81,1.00458,49.3306,'France','Rouen-Les-Essarts');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(54,67,0.224231,47.95,'France','Le Mans');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(55,88,3.93083,49.2542,'France','Reims-Gueux');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(56,15,27.8736,-33.0486,'South Africa','Prince George Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(57,676,14.7478,47.2039,'Austria','Zeltweg');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(58,20,-2.94056,53.4769,'UK','Aintree');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(59,28,-8.67325,41.1705,'Portugal','Circuito da Boavista');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(60,470,-117.273,33.937,'USA','Riverside International Raceway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(61,53,13.2514,52.4806,'Germany','AVUS');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(62,158,-9.20306,38.7197,'Portugal','Monsanto Park Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(63,18,-81.3483,27.4547,'USA','Sebring International Raceway');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(64,19,-7.6875,33.5786,'Morocco','Ain Diab');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(65,129,14.1508,42.475,'Italy','Pescara Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(66,551,7.40194,46.9589,'Switzerland','Circuit Bremgarten');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(67,85,2.11667,41.3903,'Spain','Circuit de Pedralbes');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(68,194,77.5331,28.3487,'India','Buddh International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(69,161,-97.6411,30.1328,'USA','Circuit of the Americas');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(70,678,14.7647,47.2197,'Austria','Red Bull Ring');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(71,2,39.9578,43.4057,'Russia','Sochi Autodrom');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(73,-7,49.8533,40.3725,'Azerbaijan','Baku City Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(75,108,-8.6267,37.227,'Portugal','Autódromo Internacional do Algarve');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(76,255,11.3719,43.9975,'Italy','Autodromo Internazionale del Mugello');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(77,15,39.1044,21.6319,'Saudi Arabia','Jeddah Corniche Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(78,12,51.4542,25.49,'Qatar','Losail International Circuit');
INSERT INTO circuits (circuitID, circuitAltitude, circuitLongitude, circuitLatitude, circuitCountry, circuitName) VALUES(79,0,-80.2389,25.9581,'USA','Miami International Autodrome');
